### ISSUE TITLE
stickler continuous integration not running 

### ISSUE THREAD

**Issue by igakigongo** [igakigongo/js-restaurant#3]
I have tried everything and I have given up. please help me out, look at the repository for details.

**Comment by ghost** [comment]
It was a great effort at this morning team meeting to solve this stickler issue.
I hope you could also take eslint.json base automatic change option in your local machine.

**Comment by grace-mugoiri** [comment]
next time make sure master has stickler and eslint files there :)

**Comment by igakigongo** [comment]
Thanks for your help, yes, after all the hustle we realized that the solution was to make sure that the stickler file is added to the master branch as soon as possible, or during repository initialization.
